# Generated by Django 4.1.9 on 2023-05-25 11:31

import devsearch_01.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("about", models.TextField()),
                (
                    "profile_image",
                    models.ImageField(
                        default=devsearch_01.core.models.get_default_image_path,
                        upload_to=devsearch_01.core.models.get_image_location,
                    ),
                ),
                ("location", models.CharField(max_length=250)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
