# Generated by Django 4.1.9 on 2023-05-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_account_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
