# Generated by Django 4.1.9 on 2023-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_skill_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="location",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
