# Generated by Django 4.1.9 on 2023-05-29 19:18

import devsearch_01.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_alter_account_about_alter_account_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.ImageField(
                        default=devsearch_01.core.models.get_default_project_image_path,
                        upload_to=devsearch_01.core.models.get_project_image_location,
                        verbose_name="Project Image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, default="Blank", max_length=250, null=True)),
                ("about", models.TextField(blank=True, null=True)),
                ("link", models.URLField(blank=True, help_text="a link the deployed project", null=True)),
                ("image_project", models.ManyToManyField(blank=True, null=True, to="core.image")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tool", models.CharField(max_length=250)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.project")),
            ],
        ),
    ]
