# Generated by Django 4.1.9 on 2023-05-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_project_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(default="/#/", help_text="a link the deployed project"),
        ),
    ]
