# Generated by Django 4.1.9 on 2023-05-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_project_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(blank=True, help_text="a link the deployed project"),
        ),
    ]
