# Generated by Django 4.1.9 on 2023-05-31 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_project_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image_project",
        ),
        migrations.AddField(
            model_name="image",
            name="project",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="core.project"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(help_text="a link the deployed project"),
        ),
    ]
